#!/usr/bin/env python3
from pathlib import Path
p=Path('/home/data-gxu/acm/egolink2026-main/code/track2/codex/scripts/run_v8_validation.py')
s=p.read_text(encoding='utf-8')
# Add env-file parser after SCENARIO_SPECS.
s=s.replace('''SCENARIO_SPECS = {\n    'smoke': [('retail',9,[1]), ('restaurant',4,[1]), ('order',1,[1]), ('kitchen',2,[1])],\n}\n\n\n''','''SCENARIO_SPECS = {\n    'smoke': [('retail',9,[1]), ('restaurant',4,[1]), ('order',1,[1]), ('kitchen',2,[1])],\n}\n\n\ndef load_shell_env_file(path: Path) -> Dict[str, str]:\n    out: Dict[str, str] = {}\n    if not path.exists():\n        return out\n    for line in path.read_text(encoding='utf-8').splitlines():\n        line = line.strip()\n        if not line or line.startswith('#') or not line.startswith('export '):\n            continue\n        body = line[len('export '):]\n        if '=' not in body:\n            continue\n        key, value = body.split('=', 1)\n        value = value.strip().strip('\\"').strip("'")\n        out[key.strip()] = value\n    return out\n\n\n''')
old="""    env = os.environ.copy()\n    env.update({\n        'CODEX_ROOT': str(CODEX),\n        'EGO_ROOT': str(EGO),\n"""
new="""    env = os.environ.copy()\n    env.update(load_shell_env_file(CODEX / 'state' / '.openai_env'))\n    base_url = env.get('TRACK2_OPENAI_BASE_URL') or env.get('SERVICE_MODEL_API_BASE') or 'https://ai-pixel.online/v1'\n    api_key = env.get('OPENAI_API_KEY', '')\n    env.update({\n        'CODEX_ROOT': str(CODEX),\n        'EGO_ROOT': str(EGO),\n        'SERVICE_MODEL_BACKEND': 'openai_compatible_chat',\n        'SERVICE_MODEL_NAME': model,\n        'SERVICE_MODEL_API_BASE': base_url,\n        'SERVICE_MODEL_API_KEY': api_key,\n        'USER_AGENT_API_BASE_URL': base_url,\n        'USER_AGENT_API_KEY': api_key,\n        'USER_MODEL_NAME': model,\n        'TRACK2_USER_USE_OPENAI': '0',\n        'TRACK2_USE_OPENAI_GPT55': '0',\n        'TRACK2_GPT55_STRUCTURED_OUTPUT': '0',\n        'TRACK2_ENABLE_VISUAL_CACHE': '1',\n        'TRACK2_TEXT_ONLY_VISUAL_CONTEXT': '1',\n        'TRACK2_USE_VIDEO': '0',\n        'TRACK2_MAX_TURNS': env.get('TRACK2_MAX_TURNS','6'),\n        'TRACK2_DEFAULT_MAX_TOKENS': env.get('TRACK2_DEFAULT_MAX_TOKENS','2048'),\n        'TRACK2_CONNECT_TIMEOUT': env.get('TRACK2_CONNECT_TIMEOUT','10'),\n        'TRACK2_READ_TIMEOUT': env.get('TRACK2_READ_TIMEOUT','240'),\n        'TRACK2_API_MAX_RETRIES': env.get('TRACK2_API_MAX_RETRIES','1'),\n        'TRACK2_TEMPERATURE': env.get('TRACK2_TEMPERATURE','0.1'),\n"""
s=s.replace(old,new)
# Remove unused prefix block that only sourced in shell (not used by subprocess).
s=s.replace('''    # Load endpoint env without printing it.\n    env_file = CODEX / 'state' / '.openai_env'\n    prefix = ''\n    if env_file.exists():\n        prefix = f'set -a; source {env_file}; set +a; '\n''','')
p.write_text(s,encoding='utf-8')
